version: '3.8'

services:
  questdb:
    image: questdb/questdb:7.0.1
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
    volumes:
      - ./questdb_data:/var/lib/questdb

  feeder:
    build:
      context: ./FEEDER
    depends_on:
      - questdb
    environment:
      - QUESTDB_HOST=questdb
      - QUESTDB_PORT=9009